FROM node:14-alpine as dev
WORKDIR /app

COPY ./package*.json ./
RUN npm ci

COPY . .

CMD [ "npm", "run", "dev" ]

FROM node:14-alpine as prod
WORKDIR /app

COPY ./package*.json ./
RUN npm ci

COPY . .

RUN npm run build

CMD [ "npm", "start" ]
