version: "3.8"

services:
  database:
    image: postgres:14
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: audio-player
      POSTGRES_USER: aruzo
      POSTGRES_PASSWORD: haslo123
  api:
    build: ./api
    volumes:
      - ./api:/app
      - /app/node_modules
      - media:/app/media
    environment:
      PORT: 4000
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: audio-player
      DB_USER: aruzo
      DB_PASS: haslo123
    depends_on:
      - database
  client:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      WATCHPACK_POLLING: "true"
    depends_on:
      - api
  nginx:
    image: nginx:1.15
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - media:/usr/share/nginx/media
    depends_on:
      - client
      - api

volumes:
  database:
  media:
