version: "3.8"

services:
  database:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: audio-player
      POSTGRES_USER: aruzo
      POSTGRES_PASSWORD: haslo123
  api:
    build:
      context: ./api
      target: dev
    restart: always
    volumes:
      - ./api:/app
      - /app/node_modules
      - media:/app/media
    environment:
      PORT: 4000
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: audio-player
      DB_USER: aruzo
      DB_PASS: haslo123
    depends_on:
      - database
  frontend:
    build:
      context: ./frontend
      target: dev
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api
  nginx:
    image: nginx:1.15
    restart: always
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - media:/usr/share/nginx/media
    depends_on:
      - frontend
      - api

volumes:
  database:
  media:
