version: "3.8"

services:
  database:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: audio-player
      POSTGRES_USER: aruzo
      POSTGRES_PASSWORD: haslo123
  api:
    build:
      context: ./api
      target: prod
    restart: always
    volumes:
      - media:/app/media
    environment:
      PORT: 4000
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: audio-player
      DB_USER: aruzo
      DB_PASS: haslo123
    depends_on:
      - database
  client:
    build:
      context: ./client
      target: prod
    volumes:
      - client:/app/build
    depends_on:
      - api
  nginx:
    image: nginx:1.15
    restart: always
    ports:
      - 80:80
      - 443:80
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
      - media:/usr/share/nginx/media
      - client:/usr/share/nginx/client
    depends_on:
      - api

volumes:
  database:
  media:
  client:
